services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # env_file:
    #   - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      # 中国大陆地区nextcloud的应用商店一般需要代理才能访问，此处为代理配置
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db
      - redis
      - proxy
    dns:
    - 8.8.8.8
    - 4.4.4.4

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:z,ro
      # NOTE: The `volumes` included here should match those of the `app` container (unless you know what you're doing)
    # environment:
      # - VIRTUAL_HOST=172.16.105.110.sslip.io
      # - LETSENCRYPT_HOST=
      # - LETSENCRYPT_EMAIL=
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code
    environment:
      - extra_params=${EXTRA_PARAMS}
    tty: true
    restart: unless-stopped
    networks:
      - proxy-tier
      
  proxy:
    image: nginx
    restart: always
    ports:
      # - 80:80
      - 443:443
      # - 9980:9980
    # labels:
    #   - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - certs:/etc/nginx/certs:z,ro
      - ./nginx-conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-tier

 #self signed
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
    # 将 172.16.105.110.sslip.io 换成自己的内网域名，如果如果没有域名，将 172.16.105.110.sslip.io 换成 your_ip_address.sslip.io 
      - SSL_SUBJECT=${DOMAIN_NAME}
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/${DOMAIN_NAME}.key
      - SSL_CSR=/certs/${DOMAIN_NAME}.csr
      - SSL_CERT=/certs/${DOMAIN_NAME}.crt
    networks:
     - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  # acme:
  # vhost.d:
  # html:

networks:
  proxy-tier: